<template>
  <div class="container text-2xl pl-96 pr-96 font-extrabold text-white text-center mt-12 bg-slate-900 rounded-xl shadow pt-4 mb-8">
    <div class="row pl-12 pr-12">
      <div class="col-md">
      <div id="faraday-law-calculator">
        <div id="tool-form">
          <div class="form-group">
            <div class="row">
              <div class="col-sm-4 col-xs-12">
                <label class="control-label">Number of Turns (N):</label>
              </div>
              <div class="col-sm-6 col-xs-12">
                <input v-model="numberOfTurnsNew.value" @input="checkNumberOfInputs(numberOfTurnsNew)"
                       :disabled="disableInput(numberOfTurnsNew)" :type="this.calculatedValue == numberOfTurnsNew
                       ? 'text' : 'number'"
                       class="rounded-pill form-control bg-blue-500 mb-4 text-center" />
              </div>
              <div class="col-sm-2"></div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-4 col-xs-12">
                <label class="control-label">Change in Magnetic Flux (dΦ):</label
                >
              </div>
              <div class="col-sm-6 col-xs-12">
                <input v-model="changeInMagneticFluxNew.value" @input="checkNumberOfInputs(changeInMagneticFluxNew)"
                       :disabled="disableInput(changeInMagneticFluxNew)" :type="this.calculatedValue == changeInMagneticFluxNew
                       ? 'text' : 'number'"
                       class="rounded-pill form-control bg-blue-500 mb-4 text-center" />
              </div>
              <div class="col-sm-2">
                <select v-model="changeInMagneticFluxNew.unit" class="form-control text-center">
                  <option v-for="unit in changeInMagneticFluxUnitsNew" :key="unit.text" :value="unit.value" v-text="unit.text"></option>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-4 col-xs-12">
                <label class="control-label">Time (dt):</label>
              </div>
              <div class="col-sm-6 col-xs-12">
                <input v-model="timeNew.value" @input="checkNumberOfInputs(timeNew)" :disabled="disableInput(timeNew)"
                       :type="this.calculatedValue == timeNew ? 'text' : 'number'"
                       class="rounded-pill form-control mb-4 text-center" />
              </div>
              <div class="col-sm-2">
                <select v-model="timeNew.unit" class="text-center form-control">
                  <option v-for="unit in timeUnitsNew" :key="unit.text" :value="unit.value" v-text="unit.text"></option>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-4 col-xs-12 mb-4">
                <label class="control-label">Induced EMF (ϵ):</label>
              </div>
              <div class="col-sm-6 col-xs-12 mb-4">
                <input v-model="inducedEMFNew.value" @input="checkNumberOfInputs(inducedEMFNew)"
                       :disabled="disableInput(inducedEMFNew)" :type="this.calculatedValue == inducedEMFNew
                       ? 'text' : 'number'"
                       class="rounded-pill form-control mb-2 text-center mb-4" />
              </div>
              <div class="col-sm-2 mb-4">
                <select v-model="inducedEMFNew.unit" class="text-center form-control">
                  <option v-for="unit in inducedEMFUnitsNew" :key="unit.text" :value="unit.value" v-text="unit.text"></option>
                </select>
              </div>
            </div>
          </div>
          <div class="col-xs-12 mb-4">
            <div class="form-group">
              <button :disabled="disabledNew" @click="calculateNew" class="btn btn-primary">
                Calculate
              </button>
              <button @click="resetInputs" class="btn btn-primary">
                Reset
              </button>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <div class="container pl-96 pr-96">
    <p class="text-xl">
      The application of this calculator is when trying to understand the force and voltage generated by a changing magnetic field around a closed loop. You can enter any three of the four variables:
    </p>
    <ul class="text-xl">
      <li>The number of turns of a coil</li>
      <li>The change in magnetic flux</li>
      <li>The time period for the change</li>
      <li>The EMF</li>
    </ul>
    <p class="text-xl">From there, the calculator will return the result for the fourth variable.
    </p>
    <p class="text-3xl font-extrabold">Faraday's Law Equation and Definition
    </p>
    <p class="text-xl">Faraday’s law of electromagnetic induction states that any change in a magnetic field will induce an electromotive force in a conductive coil that is directly proportional to the rate of change in the inducing magnetic field. This EMF, measured in volts, will also create a current flow. Faraday’s equation only tells us the magnitude of the EMF, not the polarity:
    </p>
    <div class="d-flex text-2xl mb-4 mt-4 justify-content-center align-items-center">
      <vue-mathjax :formula="formula" />
    </div>
    <p class="text-xl">Where:</p>
    <ul class="text-xl">
      <li>ε = the electromotive force, in volts</li>
      <li>N = the number of turns in a coil of wire</li>
      <li>dθ = the change in magnetic flux, in webers</li>
      <li>dt = the time over which the change in flux occurred, in seconds</li>
    </ul>
    <p class="text-3xl font-extrabold">Lenz’s Law Equation and Definition
    </p>
    <p class="text-xl">
      To determine the polarity of the induced EMF, we must turn to Lenz’s law which states that when a changing magnetic field induces a current in a conducting coil, the induced current will generate a magnetic field that opposes the inducing magnetic field. To put it simply, the induced current opposes the changing magnetic flux which is producing it, as shown in Figure 1.
      <br><br>When the north pole of the magnet in the figure above moves closer to or further from the loop, an EMF will be created with polarity such that the induced current in the loop will create a magnetic field that opposes the changing magnetic field from the magnet.
      Putting together Faraday’s equation (magnitude) and Lenz’s equation (polarity), we get the following:
    </p>
    <div class="d-flex text-2xl mb-4 mt-4 justify-content-center align-items-center mb-12">
      <vue-mathjax  :formula="formula1"/>
    </div>
  </div>
</template>

<script>
export default {
  name: "faradaylaw",
  data() {
    return {
      numberOfTurnsNew: { value: null, unit: 1 },
      changeInMagneticFluxNew: { value: null, unit: 1 },
      timeNew: { value: null, unit: 1 },
      inducedEMFNew: { value: null, unit: 1 },
      inputValues: [],
      calculatedValue: null,
      areaLoopValue: "",
      areaLoopUnit: "cm",
      numberOfLoops: "",
      magneticField: "",
      time: "",
      timeUnit: "sec",
      inducedVoltage: "",
      magneticFlux: "",
      formula: '$$\\epsilon = N \\frac{d\\theta}{dt}$$',
      formula1: '$$\\epsilon = -N \\frac{d\\theta}{dt}$$',
    }
  },
  computed: {
    changeInMagneticFluxUnitsNew() {
      return [
        {value: 1e6, text: "MWb"},
        {value: 1e3, text: "kWb"},
        {value: 1, text: "Wb"},
        {value: 0.001, text: "mWb"},
        {value: 1e-6, text: "uWb"},
      ];
    },
    timeUnitsNew() {
      return [
        {value: 3600, text: "hr"},
        {value: 60, text: "min"},
        {value: 1, text: "s"},
        {value: 0.001, text: "ms"},
        {value: 1e-6, text: "us"},
        {value: 1e-9, text: "ns"},
        {value: 1e-12, text: "ps"},
      ];
    },
    inducedEMFUnitsNew() {
      return [
        {value: 1e6, text: "MV"},
        {value: 1e3, text: "kV"},
        {value: 1, text: "V"},
        {value: 0.001, text: "mV"},
        {value: 1e-6, text: "uV"},
        {value: 1e-9, text: "nV"},
        {value: 1e-12, text: "pV"},
      ];
    },
    disabledNew() {
      return 3 != this.inputValues.length;
    },
    areaLoopUnitOptions() {
      return [
        {value: "mm", text: "mm²", convert: 0.01},
        {value: "cm", text: "cm²", convert: 1},
        {value: "dm", text: "dm²", convert: 100},
        {value: "m", text: "m²", convert: 1e4},
        {value: "km", text: "km²", convert: 1e10},
        {value: "in", text: "in²", convert: 6.4516},
        {value: "ft", text: "ft²", convert: 929.03},
        {value: "yd", text: "yd²", convert: 8361.27},
        {value: "mi", text: "mi²", convert: 259e8},
      ];
    },
    timeUnitOptions() {
      return [
        {value: "sec", text: "seconds (sec)", convert: 1},
        {value: "min", text: "minutes (min)", convert: 60},
        {value: "hrs", text: "hours (hrs)", convert: 3600},
        {value: "day", text: "days (day)", convert: 86400},
        {value: "wks", text: "weeks (wks)", convert: 604800},
        {value: "mos", text: "months (mos)", convert: 2628e3},
        {value: "yrs", text: "years (yrs)", convert: 31535965.44},
      ];
    },
  },
  methods: {
    checkNumberOfInputs(e) {
      if (null == e.value || "" == e.value) {
        if ((null != this.calculatedValue && (this.inputValues.push(this.calculatedValue), (this.calculatedValue = null)), this.inputValues.includes(e))) {
          var t = this.inputValues.indexOf(e);
          -1 !== t && this.inputValues.splice(t, 1);
        }
      } else this.inputValues.includes(e) || (this.inputValues.length < 4 || ((this.inputValues[0].value = null), this.inputValues.shift()), this.inputValues.push(e));
    },
    disableInput(e) {
      return (("" == e.value || null == e.value) && this.inputValues.length >= 3) || (e == this.calculatedValue && this.inputValues.length >= 3);
    },
    resetInputs() {
      (this.numberOfTurnsNew.value = null), (this.changeInMagneticFluxNew.value = null), (this.timeNew.value = null), (this.inducedEMFNew.value = null), (this.inputValues = []), (this.calculatedValue = null);
    },
    calculateNew() {
      (null != this.numberOfTurnsNew.value && "" != this.numberOfTurnsNew.value && this.calculatedValue != this.numberOfTurnsNew) ||
      ((this.numberOfTurnsNew.value = this.formatOutput(
        Math.abs((this.inducedEMFNew.value * this.inducedEMFNew.unit * (this.timeNew.value * this.timeNew.unit)) / (this.changeInMagneticFluxNew.value * this.changeInMagneticFluxNew.unit)) / this.numberOfTurnsNew.unit
      )),
        (this.calculatedValue = this.numberOfTurnsNew)),
      (null != this.changeInMagneticFluxNew.value && "" != this.changeInMagneticFluxNew.value && this.calculatedValue != this.changeInMagneticFluxNew) ||
      ((this.changeInMagneticFluxNew.value = this.formatOutput(
        (-this.inducedEMFNew.value * this.inducedEMFNew.unit * (this.timeNew.value * this.timeNew.unit)) / (this.numberOfTurnsNew.value * this.numberOfTurnsNew.unit) / this.changeInMagneticFluxNew.unit
      )),
        (this.calculatedValue = this.changeInMagneticFluxNew)),
      (null != this.timeNew.value && "" != this.timeNew.value && this.calculatedValue != this.timeNew) ||
      ((this.timeNew.value = this.formatOutput(
        Math.abs((this.numberOfTurnsNew.value * this.numberOfTurnsNew.unit * (this.changeInMagneticFluxNew.value * this.changeInMagneticFluxNew.unit)) / (this.inducedEMFNew.value * this.inducedEMFNew.unit)) /
        this.timeNew.unit
      )),
        (this.calculatedValue = this.timeNew)),
      (null != this.inducedEMFNew.value && "" != this.inducedEMFNew.value && this.calculatedValue != this.inducedEMFNew) ||
      ((this.inducedEMFNew.value = this.formatOutput(
        (this.numberOfTurnsNew.value * this.numberOfTurnsNew.unit * -1 * ((this.changeInMagneticFluxNew.value * this.changeInMagneticFluxNew.unit) / (this.timeNew.value * this.timeNew.unit))) /
        this.inducedEMFNew.unit
      )),
        (this.calculatedValue = this.inducedEMFNew));
    },
    formatOutput(e) {
      return isNaN(e) || "" == e || null == e ? e : parseFloat(e.toFixed(4));
    },
    getAreaUnitValue() {
      var e,
        t = this.areaLoopUnit,
        n = a(this.areaLoopUnitOptions);
      try {
        for (n.s(); !(e = n.n()).done;) {
          var r = e.value;
          if (r.value == t) return r.convert;
        }
      } catch (e) {
        n.e(e);
      } finally {
        n.f();
      }
    },
    getTimeUnitValue() {
      var e,
        t = this.timeUnit,
        n = a(this.timeUnitOptions);
      try {
        for (n.s(); !(e = n.n()).done;) {
          var r = e.value;
          if (r.value == t) return r.convert;
        }
      } catch (e) {
        n.e(e);
      } finally {
        n.f();
      }
    },
    round(e) {
      return e.toFixed(20).match(/^-?\d*\.?0*\d{0,4}/)[0];
    },
    calculate() {
      var e = this.getAreaUnitValue() * this.areaLoopValue;
      this.magneticFlux = this.magneticField * e * Math.pow(this.numberOfLoops, -4);
      var t = this.getTimeUnitValue() * this.time;
      this.inducedVoltage = (-this.numberOfLoops * this.magneticFlux) / t;
    },
  },
}
</script>

<style scoped>
input[type=number] {
  background-color: rgb(30 41 59);
  border-color: rgb(30 41 59);
  color: white;
}

</style>
